### PR TITLE
FreeBSD Compatibility

### PR DESCRIPTION
**Pull request by 5u623l20**
For sockaddr_in FreeBSD needs netinet/in.h

### CODE REVIEW

**Comment by sonertari** [comment]
Thanks @5u623l20 for the pr. I have changed the target branch and merged your patches to the develop branch.

**Comment by sonertari** [comment]
@5u623l20, we should call available_fds() on FreeBSD for the correct fix, please see my last commint on the develop branch.

Btw, do you know if DragonflyBSD has getdtablecount()? If not, we should do the same for it too.

**Comment by sonertari** [comment]
The commits adee22db098969afbcde88f3ea9205588d97cf8f and 1c8a837df1fb4b6780d77ec14517619fe0756fa0 merge this pr and more on the develop branch. So closing this pr now.

**Comment by 5u623l20** [comment]
> @5u623l20, we should call available_fds() on FreeBSD for the correct fix, please see my last commit on the develop branch.
> 
> Btw, do you know if DragonflyBSD has getdtablecount()? If not, we should do the same for it too.
Hi, I am not sure why I have missed the notifications. I am not a vivid user of DragonflyBSD. But as a fork of FreeBSD I believe it doesn't have.

0.7.0 will be in the tree hopefully within an hour. One more thing I was trying to guess is whether if it possible to integrate hardware assisted decryption/encryption using Intel QAT or maybe Chelsio NIC cards crypto accelerators. Then comes using netmap to transfer the packets rather than sockets. Endless possibilities.

**Comment by sonertari** [comment]
Thanks for the info. Since I don't have such hardware and/or development environment for those, I have no idea. But as I mentioned on the issue #9, I would use such solutions if I were developing an appliance (Linux or FreeBSD).

**Comment by 5u623l20** [comment]
> Thanks for the info. Since I don't have such hardware and/or development environment for those, I have no idea. But as I mentioned on the issue #9, I would use such solutions if I were developing an appliance (Linux or FreeBSD).


Let me know if you come up with such a plan. I would like to contribute as much as possible.

**Pull request closed without merging**
